# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-15 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20160926_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipeImage',
            field=models.FileField(upload_to=''),
        ),
    ]
