# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-26 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20161015_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='directions',
            field=models.TextField(max_length=10000),
        ),
    ]
