# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-26 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20161025_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(max_length=20000),
        ),
    ]
