# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-01 08:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0006_auto_20161025_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='courseType',
            field=models.CharField(choices=[('N/A', 'N/A'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Lunch & Dinner', 'Lunch & Dinner')], max_length=14),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='mealType',
            field=models.CharField(choices=[('Appetizer', 'Appetizer'), ('Soup & Salad', 'Soup & Salad'), ('Entree', 'Entree'), ('Dessert', 'Dessert'), ('Beverage', 'Beverage')], max_length=15),
        ),
    ]
