# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-01 20:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20161201_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.TextField(default=django.utils.timezone.now, max_length=20000),
            preserve_default=False,
        ),
    ]
